DROP TABLE MEMBER;

CREATE TABLE MEMBER( 
    USER_NO NUMBER PRIMARY KEY,             -- 회원 번호
    USER_ID VARCHAR2(30) NOT NULL UNIQUE,    -- 아이디
    USER_PWD VARCHAR2(30) NOT NULL,            -- 비밀번호
    USER_NAME VARCHAR2(20) NOT NULL,               -- 아이디
    GENDER CHAR(1) CHECK(GENDER IN('M','F')),       --성별
    AGE NUMBER,
    EMAIL VARCHAR2(30),
    PHONE CHAR(11),
    ADDRESS VARCHAR2(100),
    HOBBY VARCHAR2(50),
    EMROLL_DATE DATE DEFAULT SYSDATE NOT NULL
);

CREATE SEQUENCE SEQ_USERNO
NOCACHE;